---
title: Analysis of ARPAV Temperature Data
author: Guglielmo Bordin, Alessio Pitteri
date: "`r gsub('^0', '', format(Sys.Date(), '%d %B %Y'))`"
output:
    rmdformats::robobook:
        fig_width: 8
        fig_height: 5
        thumbnails: false
        lightbox: true
        gallery: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(message = FALSE, dev = "svg")
```

```{r}
library(tidyverse)
library(R2jags)
library(bayesplot)

global_seed <- 30172
set.seed(global_seed)

global_font <- "Roboto Condensed"
theme_set(theme_minimal(base_size = 15, base_family = global_font))
my_pal <- wesanderson::wes_palette("Zissou1", 5)[c(1, 3, 5)]
```

```{r}
get_daily_data <- function(station) {
    require(readr)

    fname <- paste0("./data/temp/", station, ".csv")

    read_csv(
        fname,
        col_names = c("date", "min", "avg", "max"),
        skip = 1,
        show_col_types = FALSE
    ) |> na.omit()
}

get_monthly_data <- function(station) {
    require(dplyr)
    require(lubridate)

    get_daily_data(station) |>
        mutate(
            year = year(.data$date),
            month = month(.data$date, label = TRUE)
        ) |>
        group_by(year, month) |>
        summarize(
            min = mean(.data$min),
            avg = mean(.data$avg),
            max = mean(.data$max)
        )
}

temp_change_heatmaps <- function(station, avg_window) {
    require(forcats)
    require(ggplot2)
    require(scales)
    require(stringr)
    require(wesanderson)

    data <- get_monthly_data(station)

    years <- unique(data$year)

    baseline <- data |>
        filter(.data$year <= years[avg_window]) |>
        group_by(.data$month) |>
        summarize(
            min = mean(.data$min),
            avg = mean(.data$avg),
            max = mean(.data$max)
        )

    station_name <- station |>
        str_split_1("_") |>
        paste(collapse = " ") |>
        str_to_title() |>
        paste("station")

    temperature_plt <- data |>
        inner_join(baseline, by = "month") |>
        mutate(avg = .data$avg.x - .data$avg.y) |>
        ggplot() +
            geom_tile(
                aes(x = .data$year, y = fct_rev(.data$month),
                fill = .data$avg)
            ) +
            annotate(
                geom = "rect",
                xmin = years[1] - 0.5, xmax = years[avg_window] + 0.5,
                ymin = 12.5, ymax = 0.5,
                fill = "grey50", alpha = 0.4
            ) +
            scale_x_continuous(
                breaks = pretty_breaks(),
                expand = c(0, 0)
            ) +
            scale_fill_gradientn(
                colours = wes_palette("Zissou1", 10, "continuous")
            ) +
            labs(
                x = "Year", y = "Month", fill = "Deviation (°C)",
                title = paste0(
                    "Deviation of the average monthly ",
                    "temperature w.r.t. the ",
                    years[1], "-", years[avg_window], " period"
                ),
                subtitle = station_name
            )

    excursion_plt <- data |>
        inner_join(baseline, by = "month") |>
        mutate(
            diff = .data$max.x - .data$min.x - .data$max.y + .data$min.y
        ) |>
        ggplot() +
            geom_tile(
                aes(x = .data$year, y = fct_rev(.data$month),
                fill = diff)
            ) +
            annotate(
                geom = "rect",
                xmin = years[1] - 0.5, xmax = years[avg_window] + 0.5,
                ymin = 12.5, ymax = 0.5,
                fill = "grey50", alpha = 0.4
            ) +
            scale_x_continuous(
                breaks = pretty_breaks(),
                expand = c(0, 0)
            ) +
            scale_fill_gradientn(
                colours = wes_palette("Zissou1", 10, "continuous")
            ) +
            labs(
                x = "Year", y = "Month", fill = "Deviation (°C)",
                title = paste0(
                    "Deviation of the average monthly thermal ",
                    "excursion w.r.t. the ",
                    years[1], "-", years[avg_window], " period"
                ),
                subtitle = station_name
        )

    list(temperature = temperature_plt, excursion = excursion_plt)
}
```

```{r}
temp_change_heatmaps(station = "castelfranco_veneto", avg_window = 10)
```

```{r}
get_yearly_data <- function(station) {
    data <- get_daily_data(station)

    full_years <- data |>
        mutate(year = year(.data$date), month = month(.data$date)) |>
        group_by(year, month) |>
        count() |>
        group_by(year) |>
        filter(n() == 12) |>
        distinct(year) |>
        pull()

    data |>
        mutate(year = year(.data$date)) |>
        filter(year %in% full_years) |>
        group_by(year) |>
        summarize(
            min = mean(.data$min),
            avg = mean(.data$avg),
            max = mean(.data$max)
        )
}
```

```{r}
lin_model <- "
    model {
        tau <- 1 / sigma^2

        for (i in 1:length(year)) {
            mu[i] <- a + b * year[i]
            avg[i] ~ dnorm(mu[i], tau)
        }

        a ~ dnorm(0, 1e-6)
        b ~ dnorm(0, 1e-6)
        sigma ~ dexp(0.0001)
    }"

lin_pars <- c("a", "b", "sigma")

const_model <- "
    model {
        tau <- 1 / sigma^2

        for (i in 1:length(year)) {
            avg[i] ~ dnorm(a, tau);
        }

        a ~ dnorm(0, 1e-6)
        sigma ~ dexp(0.0001);
    }"

const_pars <- c("a", "sigma")

quad_model <- "
    model {
        tau <- 1 / sigma^2

        for (i in 1:length(year)) {
            mu[i] <- a + b * year[i] + c * year[i] * year[i]
            avg[i] ~ dnorm(mu[i], tau)
        }

        a ~ dnorm(0, 1e-6)
        b ~ dnorm(0, 1e-6)
        c ~ dnorm(0, 1e-6)
        sigma ~ dexp(0.0001)
    }"

quad_pars <- c("a", "b", "c", "sigma")

init_variables <- function(model) {
    if (model == lin_model) {
        function() {
            list(
                a = runif(1, -200, 0),
                b = runif(1, 0, 1),
                sigma = runif(1, 0, 1)
            )
        }
    } else if (model == const_model) {
        function() {
            list(
                a = runif(1, -200, 0),
                sigma = runif(1, 0, 1)
            )
        }
    } else if (model == quad_model) {
        function() {
            list(
                a = runif(1, -200, 0),
                b = runif(1, 0, 1),
                c = runif(1, 0, 1),
                sigma = runif(1, 0, 1)
            )
        }
    }
}

regression <- function(station, model, params) {
    R2jags::jags(
        data = get_yearly_data(station),
        inits = init_variables(model),
        parameters.to.save = params,
        model.file = textConnection(model),
        n.chains = 3,
        n.iter = 100000,
        n.burnin = 2000,
        n.thin = 10,
        DIC = FALSE
    ) |> coda::as.mcmc()
}

plot_chains <- function(chain, params) {
    trace_plt <- mcmc_trace(
        chain, pars = params,
        facet_args = list(nrow = length(params), labeller = label_parsed)
    ) +
        facet_text(size = 15) +
        labs(title = "Traces") +
        bayesplot::theme_default(base_size = 15, base_family = global_font)

    dens_plt <- mcmc_dens_overlay(
        chain, pars = params,
        facet_args = list(nrow = length(params), labeller = label_parsed)
    ) +
        facet_text(size = 15) +
        labs(title = "Densities") +
        bayesplot::theme_default(base_size = 15, base_family = global_font)

    gridExtra::grid.arrange(trace_plt, dens_plt, ncol = 2)
}
```

```{r}
lin_chain <- regression("porto_tolle", lin_model, lin_pars)

lin_df <- do.call(rbind.data.frame, lin_chain)
sig_level <- quantile(lin_df$b, probs = 0.05)

ggplot(lin_df) +
    geom_density(aes(b), colour = my_pal[1], fill = my_pal[1], alpha = 0.5) +
    geom_area(
        aes(x, y),
        data = tibble(
            x = density(lin_df$b, from = -0.01, to = sig_level)$x,
            y = density(lin_df$b, from = -0.01, to = sig_level)$y),
        colour = my_pal[3], fill = my_pal[3], alpha = 0.5
    ) +
    geom_vline(xintercept = 0, colour = my_pal[2], linewidth = 0.8) +
    coord_cartesian(expand = FALSE)
```

```{r}
quad_chain <- regression("porto_tolle", quad_model, quad_pars) |>
    plot_chains(quad_pars)
```

```{r}
lm_fit <- lm(avg ~ year + I(year^2), get_yearly_data("porto_tolle"))
lm_params <- summary(lm_fit)$coefficients[, 1]
lm_errs <- summary(lm_fit)$coefficients[, 2]

quad_model <- sprintf("
    model {
        tau <- 1 / sigma^2

        for (i in 1:length(year)) {
            mu[i] <- a + b * year[i] + c * year[i] * year[i]
            avg[i] ~ dnorm(mu[i], tau)
        }

        a ~ dnorm(%e, %e)
        b ~ dnorm(%e, %e)
        c ~ dnorm(%e, %e)
        sigma ~ dexp(0.0001)
    }",
    lm_params[1], 1 / lm_errs[1]^2,
    lm_params[2], 1 / lm_errs[2]^2,
    lm_params[3], 1 / lm_errs[3]^2
)

quad_pars <- c("a", "b", "c", "sigma")

quad_chain <- regression("porto_tolle", quad_model, quad_pars)

best_pars <- quad_chain |>
    tidybayes::tidy_draws() |>
    select(a, b, c, sigma) |>
    summarize(a = mean(a), b = mean(b), c = mean(c), sigma = mean(sigma))
```

```{r}
correlation_plot <- function(stat1, stat2) {
    df <- inner_join(
        get_yearly_data(stat1),
        get_yearly_data(stat2),
        by = "year",
        suffix = c(".s1", ".s2")
    )

    name_stat <- function(stat) {
        stat |> str_split_1("_") |> paste(collapse = " ") |> str_to_title()
    }

    name1 <- name_stat(stat1)
    name2 <- name_stat(stat2)

    plot <- ggplot(df, aes(x = .data$avg.s1, y = .data$avg.s2)) +
        geom_point(aes(colour = .data$year), size = 3) +
        ggrepel::geom_label_repel(
            aes(label = .data$year, colour = .data$year),
            data = \(x) x |> filter(row_number() %% 3 == 1),
            min.segment.length = 0,
            box.padding = 0.5
        ) +
        labs(
            x = paste(name1, "temperature (°C)"),
            y = paste(name2, "temperature (°C)"),
            colour = "Year",
            title = paste(
                "Comparison of the average yearly temperatures in",
                name1, "and", name2
            )
        )

    list(
        cor = cor(df$avg.s1, df$avg.s2, method = "pearson"),
        plot = plot
    )
}
```

```{r}
mal_rov_corr <- correlation_plot("malo", "roverchiara")

mal_rov_corr$cor
mal_rov_corr$plot
```

```{r}
get_period_data <- function(station, interval) {
    data <- get_yearly_data(station) |>
        filter(.data$year > 1980)
    data <- data[seq(1, nrow(data) - (nrow(data) %% interval)), ]
    first_year <- data$year[1]
    last_year <- data$year[nrow(data)]

    data |>
        mutate(
            period = cut(
                .data$year,
                breaks = seq(first_year, last_year + 1, interval),
                right = FALSE
            )
        ) |>
        group_by(period) |>
        summarize(
            centre = (
                as.integer(substr(as.character(unique(period)), 7, 10)) +
                as.integer(substr(as.character(unique(period)), 2, 5)) - 1
            ) / 2,
            min = mean(.data$min),
            avg = mean(.data$avg),
            max = mean(.data$max)
        )
}
```

```{r}
period_regression <- function(data, type) {
    data <- data[, c("centre", type)]

    lm_fit <- lm(as.formula(paste(type, "~ centre")), data)
    lm_pars <- summary(lm_fit)$coefficients[, 1]
    lm_errs <- summary(lm_fit)$coefficients[, 2]

    model <- sprintf("
        model {
            tau <- 1 / sigma^2

            for (i in 1:length(centre)) {
                mu[i] <- a + b * centre[i]
                %s[i] ~ dnorm(mu[i], tau)
            }

            a ~ dnorm(%f, %f)
            b ~ dnorm(%f, %f)
            sigma ~ dexp(0.0001)
        }",
        type,
        lm_pars[1], 1 / lm_errs[1]^2,
        lm_pars[2], 1 / lm_errs[2]^2
    )

    pars <- c("a", "b", "sigma")

    R2jags::jags(
        data = data,
        inits = \() list(a = rnorm(1), b = rnorm(1), sigma = runif(1)),
        parameters.to.save = pars,
        model.file = textConnection(model),
        n.chains = 3,
        n.iter = 100000,
        n.burnin = 2000,
        n.thin = 10,
        DIC = FALSE
    ) |> coda::as.mcmc()
}
```

```{r}
period_length <- 5
period_data <- get_period_data("castelfranco_veneto", period_length)
period_chain <- period_regression(period_data, "avg")

plot_chains(period_chain, lin_pars)
```

Data from SNPA:

> La stima aggiornata del rateo di variazione della temperatura media dal
> 1981 al 2019 è di +0,38 ± 0,05 °C/10 anni; il rateo di variazione della
> temperatura massima (+0,42 ± 0,06 °C/10 anni) è maggiore di quello della
> temperatura minima (+0,34 ± 0,04 °C/10 anni).

```{r}
snpa <- tibble(
    type = c("min", "avg", "max"),
    mu = c(0.34, 0.38, 0.42),
    sigma = c(0.04, 0.05, 0.06)
)

snpa_comparison <- function(chain, st_name, type, interval) {
    chain_pars <- chain |>
        tidybayes::tidy_draws() |>
        select("b") |>
        summarize(mu = mean(.data$b), sigma = sd(.data$b))

    mu_d <- chain_pars$mu - snpa$mu[snpa$type == type] / 10
    sigma_d <- sqrt(
        chain_pars$sigma^2 + (snpa$sigma[snpa$type == type] / 10)^2
    )

    cred <- qnorm(c(0.025, 0.975), mu_d, sigma_d)

    x <- mu_d + seq(-5 * sigma_d, 5 * sigma_d, length.out = 1000)

    tibble(x = x, y = dnorm(x, mu_d, sigma_d)) |>
        ggplot(aes(.data$x, .data$y)) +
            geom_area(fill = my_pal[1], alpha = 0.5) +
            geom_area(
                data = \(x) x |> filter(x < cred[1]),
                fill = my_pal[3], alpha = 0.5
            ) +
            geom_area(
                data = \(x) x |> filter(x > cred[2]),
                fill = my_pal[3], alpha = 0.5
            ) +
            geom_vline(
                xintercept = 0, colour = my_pal[2], linewidth = 0.8
            ) +
            coord_cartesian(expand = FALSE) +
            labs(
                x = "Difference of the posterior means",
                y = "Posterior distribution",
                title = paste(
                    "Compatibility test of the",
                    ifelse(
                        type == "min", "minimum",
                        ifelse(type == "max", "maximum", "average")
                    ),
                    "temperatures’ yearly increase rates"
                ),
                subtitle = paste(
                    "Difference between", st_name, "and SNPA data"
                )
            )
}
```

```{r}
snpa_comparison(period_chain, "Castelfranco Veneto", "avg", period_length)
```
```{r}
#FORECAST
#install.packages('forecast')
library(forecast)
```
```{r}
#DIFF DATASET

get_diff_data <- function(station){
  get_yearly_data(station) |>
    reframe(
      year = year,
      diff_avg = c(0,diff(avg)),
      diff_min = c(0,diff(min)),
      diff_max = c(0,diff(max))
    ) |>
    tail(-1)
    
}

forecast_prediction <- function(data_type, station, pred_years, interv=5){
  
  if(data_type == "diff"){
    df <- get_diff_data(station)
    time_series <- ts(
      data = df$diff_avg,
      frequency = 1,
      start = c(df$year[1])
    )
    aa <- Arima(time_series, order = c(5,0,5))
    print(aa)
    fc <- forecast(aa, level = c(95), h = pred_years)
  }
  
  else if(data_type == "monthly"){
    df <- get_monthly_data(station)
    time_series <- ts(
      data = df$avg,
      frequency = 12,
      start = c(df$year,as.numeric(df$month[1]))
    )
    aa <- Arima(time_series, order = c(3,0,1), seasonal=c(0,1,2), lambda = 0)
    print(aa)
    fc <- forecast(aa, level = c(95), h = pred_years*12)
  }
  
  else if(data_type == "yearly"){
    df <- get_yearly_data(station)
    time_series <- ts(
      data = df$avg,
      frequency = 1,
      start = c(df$year[1])
    )
    aa <- Arima(time_series, order = c(3,1,4))
    print(aa)
    #aa <- auto.arima(time_series)
    fc <- forecast(aa, level = c(95), h = pred_years)
  }
  
  else if(data_type == "period"){
    df <- get_period_data(station, interv)
    time_series <- ts(
      data = df$avg,
      frequency = 1/interv,
      start = c(df$centre[1])
    )
    aa <- Arima(time_series, order = c(3,1,3))
    print(aa)
    fc <- forecast(aa, level = c(95), h = as.integer(pred_years/interv))
  }
   
  gridExtra::grid.arrange(
                           autoplot(time_series) + theme_bw(base_size = 8) +
                             labs(xlab = "time",
                                  ylab = paste(data_type, "temperature trend"),
                                  title = "time series"),
                           ggAcf(time_series) + theme_bw(base_size = 8) +
                             labs(xlab = "lag",
                                  ylab = "acf",
                                  title = "acf of the time series"),
                           ggAcf(aa$residuals) +theme_bw(base_size = 8) +
                             labs(xlab = "lag",
                                  ylab = "acf",
                                  title = "acf of the residuals"),
                           autoplot(fc) + theme_bw(base_size = 8) +
                             labs(xlab = "time",
                                  ylab = paste(data_type, "temperature trend"),
                                  title = "forecast of the time series"),
                           ncol = 2
                          )
   
   return(fc)
  
}

diff_unrolling <- function(stat, py){
  
  malo_pred <- forecast_prediction(data_type = "diff", station = stat,
                             pred_years = py)
  
  start_year <- get_yearly_data(stat)$year[length(get_yearly_data(stat)$year)]
  start_temp <- get_yearly_data(stat)$avg[length(get_yearly_data(stat)$avg)]
  pred_df <- data.frame( x = seq(start_year+1, start_year+py),
                   y = start_temp + cumsum(malo_pred$mean)
                 )
  
  ggplot(data = get_yearly_data(stat)) + geom_line(aes(x = year, y = avg)) +
    geom_line(data = pred_df, aes(x = x, y = y), col = my_pal[1], linewidth = 2) +
    labs(xlab = "year", ylab = "avg temperature", title = "avg temperature prevision")
  
}

diff_unrolling("auronzo", 15)
```


```{r}
const_model <- "
    model {
        tau <- 1 / sigma^2

        for (i in 1:length(year)) {
            diff_avg[i] ~ dnorm(a, tau);
        }

        a ~ dnorm(0.04, 100)
        sigma ~ dexp(0.0001);
    }"


diff_chain <- R2jags::jags(
        data = get_diff_data("auronzo"),
        inits = function() {
            list(
                a = runif(1, -200, 0),
                sigma = runif(1, 0, 1)
            )
            },
        parameters.to.save = const_pars,
        model.file = textConnection(const_model),
        n.chains = 3,
        n.iter = 100000,
        n.burnin = 2000,
        n.thin = 10,
        DIC = FALSE
    ) |> coda::as.mcmc()

plot_chains(diff_chain, const_pars)


const_diff <- do.call(rbind.data.frame, diff_chain)
sig_level <- quantile(const_diff$a, probs = 0.05)

ggplot(const_diff) +
    geom_density(aes(a), colour = my_pal[1], fill = my_pal[1], alpha = 0.5) +
    geom_area(
        aes(x, y),
        data = tibble(
            x = density(const_diff$a, from = -0.5, to = sig_level)$x,
            y = density(const_diff$a, from = -0.5, to = sig_level)$y),
        colour = my_pal[3], fill = my_pal[3], alpha = 0.5
    ) +
    geom_vline(xintercept = 0, colour = my_pal[2], linewidth = 0.8) +
    geom_vline(xintercept = 0.04) +
    coord_cartesian(expand = FALSE)
```
